---
language: shell

env:
  - dist: karljohns0n/centos
    version: 6
    pkg_arch: x86_64
  - dist: centos
    version: 7
    pkg_arch: x86_64
  - dist: almalinux
    version: 8
    pkg_arch: x86_64
  - dist: rockylinux/rockylinux
    version: 8
    pkg_arch: x86_64

services:
  - docker

before_install:
  - docker pull karljohns0n/rpmbuild:8
  - docker pull "${dist}":"${version}"

script:
  - pkg_name=aeris-tools
  - pkg_version=$(grep "Version:" SPECS/${pkg_name}.spec|awk '{print $2}' )
  - pkg_release=$(grep "Release:" SPECS/${pkg_name}.spec|awk '{print $2}'| tr -d "%{?dist}")
  - container_id=$(cat /dev/urandom | env LC_ALL=C tr -dc 'a-zA-Z0-9' | fold -w 20 | head -n 1)

  # Build package
  - docker run --name "${container_id}" --detach --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/tmp/"${pkg_name}" karljohns0n/rpmbuild:8
  - docker exec "${container_id}" mkdir -p /tmp/"${pkg_name}"/{BUILD,RPMS,SPECS,SOURCES,SRPMS}
  - docker exec "${container_id}" spectool -g -C /tmp/"${pkg_name}"/SOURCES /tmp/"${pkg_name}"/SPECS/"${pkg_name}".spec
  - docker exec "${container_id}" mock --isolation=simple -r aeris-"${version}"-x86_64 --spec=/tmp/"${pkg_name}"/SPECS/"${pkg_name}".spec --sources=/tmp/"${pkg_name}"/SOURCES --resultdir=/tmp/"${pkg_name}"/SRPMS --buildsrpm
  - docker exec "${container_id}" mock --isolation=simple --clean -D "dist .el${version}" -r aeris-"${version}"-x86_64 --resultdir=/tmp/"${pkg_name}"/RPMS --rebuild /tmp/"${pkg_name}"/SRPMS/"${pkg_name}"-"${pkg_version}"-"${pkg_release}".el"${version}".src.rpm
  - docker exec "${container_id}" rpm -q -l -p /tmp/"${pkg_name}"/RPMS/"${pkg_name}"-"${pkg_version}"-"${pkg_release}".el"${version}"."${pkg_arch}".rpm
  - docker rm -f "${container_id}"

  # Test package
  - docker run --name "${container_id}" --detach --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/tmp/"${pkg_name}" "${dist}":"${version}"
  - docker exec "${container_id}" yum -y install https://repo.aerisnetwork.com/pub/aeris-release-"${version}".rpm
  - docker exec "${container_id}" yum install --enablerepo="aeris,aeris-testing" -y /tmp/"${pkg_name}"/RPMS/"${pkg_name}"-"${pkg_version}"-"${pkg_release}".el"${version}"."${pkg_arch}".rpm
  - docker exec "${container_id}" ls -alh /opt/aeris/tools/
  - docker exec "${container_id}" ls -alh /etc/profile.d/z-aeris.sh
  - docker rm -f "${container_id}"